name: "Locality Checker"

on: [ "push" ]

jobs:
  Build:
    uses: "./.github/workflows/docker-build.yml"
    permissions:
      contents: read
      packages: write
    secrets: "inherit"
    with:
      path: "locality-checker"
      tag: "player-wallet/cockroachdb-k8s-locality-checker"
